### PR TITLE
fixed bunjs link mistake

### PR DESCRIPTION
**Pull request by sad1go0**

### CODE REVIEW

**Comment by doniyor2109** [comment]
@sad1go0 I think it is already added?

**Comment by sad1go0** [comment]
> @sad1go0 I think it is already added?

i made mistake, i fixed it this PR. sorry about that :)

**Comment by doniyor2109** [comment]
@sad1go0 Oh ok. Can you resolve conflicts then?

**Comment by sad1go0** [comment]
> @sad1go0 Oh ok. Can you resolve conflicts then?
I think that resolved🤔. Just merge this PR
image

**Comment by doniyor2109** [comment]
@sad1go0 It shows me the conflicts somehow
Screen Shot 2022-08-31 at 12 27 20

**Comment by sad1go0** [comment]
> @sad1go0 It shows me the conflicts somehow
> Screen Shot 2022-08-31 at 12 27 20
> 

ahh, i didn't see this. i will open another PR, you can close this PR without merge.

**Pull request closed without merging**
