### PR TITLE
added elasticsearch & ekl stack community

### PR DESCRIPTION
**Pull request by akhmadiy**
Added elasticsearch uzbek community. There is also an elasticsearch representative in this community

### CODE REVIEW

**Comment by doniyor2109** [comment]
@akhmadiy Thanks for brining this group. Can we move it under `Backend` section as it is more related to backend technology?

**Comment by akhmadiy** [comment]
@doniyor2109 I suggest opening a separate section for technologies ? For example, if communities are formed for kafka rabbitmq and a number of other technologies, they will have to be opened separately.

**Comment by doniyor2109** [comment]
So for the beginning we can move to common sections

**Comment by doniyor2109** [comment]
@akhmadiy I have moved it to backend section because I could not think of any other section for it.

**Comment by akhmadiy** [comment]
@doniyor2109 Sorry I didn't see the comment !. Maybe we will open a separate section called stack. Because there are many such stacks, for example K8s or docker stack or Grafana stack. There are many more such stacks that cover several technologies.

**Pull request merged**
